"""store user uploads

Revision ID: faaa83f0de09
Revises: 42da3d9d92aa
Create Date: 2026-07-25 16:45:44.539156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faaa83f0de09'
down_revision: Union[str, Sequence[str], None] = '42da3d9d92aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_scans_image_hash'), ['image_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scans_image_hash'))
        batch_op.drop_column('image_path')
        batch_op.drop_column('image_hash')

    # ### end Alembic commands ###
